name = "redirect-profile"
main = "src/index.js"
compatibility_date = "2025-05-26"
workers_dev = false

[[routes]]
pattern = "about.alexander.xin/*"
zone_name = "alexander.xin"

[[routes]]
pattern = "bio.alexander.xin/*"
zone_name = "alexander.xin"
